services:
  gestion-de-pedidos:
    build: .
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://gestion_pedido:3306/gestion_pedido?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
    restart: always
    depends_on:
      gestion_pedido:
          condition: service_healthy
  gestion_pedido:
    image: mysql:8.0.19 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: gestion_pedido
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 2